# Generated by Django 4.0.1 on 2022-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Каталог')),
                ('text', models.TextField(default='', max_length=150, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='DentOb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Каталог2')),
                ('text', models.TextField(default='', max_length=150, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Main image'),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
