# Generated by Django 4.0.1 on 2022-03-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_dentin_dentob_alter_products_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DentIn',
        ),
    ]
