# Generated by Django 4.0.1 on 2022-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_products_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DentOb',
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service', verbose_name='Фото'),
        ),
    ]
